version: "3.7"
services:
  blockchain:
    image: block-node:latest
    networks:
        - net-blockchain
    deploy:
        endpoint_mode: dnsrr
        replicas: 5

networks:
  net-blockchain:
    driver: overlay
    external: true
